# Generated by Django 4.1.2 on 2023-03-20 08:57

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mobility_data",
            "0041_contenttype_grouptype_make_name_and_description_multilingual",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mobileunit",
            options={},
        ),
        migrations.AddField(
            model_name="mobileunit",
            name="search_column_en",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="mobileunit",
            name="search_column_fi",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="mobileunit",
            name="search_column_sv",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="mobileunit",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_column_fi"], name="mobility_da_search__0deecc_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="mobileunit",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_column_sv"], name="mobility_da_search__f31d07_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="mobileunit",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_column_en"], name="mobility_da_search__563f0a_gin"
            ),
        ),
    ]
