# Generated by Django 4.1.2 on 2023-03-21 06:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobility_data", "0043_add_mobileunit_multilingual_content_type_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobileunit",
            name="syllables_fi",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=16), default=list, size=None
            ),
        ),
    ]
