# Generated by Django 4.1.2 on 2023-03-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mobility_data", "0044_add_mobileunit_syllables_fi_column"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mobileunit",
            options={"ordering": ["-created_time"]},
        ),
    ]
