# Generated by Django 4.1.13 on 2024-06-17 06:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobility_data", "0045_contenttype_add_multilingual_search_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenttype",
            name="syllables_fi",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=16), default=list, size=None
            ),
        ),
    ]
