# Generated by Django 4.2.15 on 2024-09-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0004_iotdatasource_is_xml_alter_iotdatasource_headers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iotdatasource",
            name="headers",
            field=models.JSONField(
                blank=True,
                help_text='Request headers in JSON format, e.g., {"key1": "value1", "key2": "value2"}',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="iotdatasource",
            name="is_xml",
            field=models.BooleanField(
                default=False, help_text="If True, XML data will be converted to JSON."
            ),
        ),
        migrations.AlterField(
            model_name="iotdatasource",
            name="source_name",
            field=models.CharField(
                help_text="Three letter long identifier for the source. Set the identifier as an argument to the Celery task that fetches the data.",
                max_length=3,
                unique=True,
            ),
        ),
    ]
