# Generated by Django 4.2.15 on 2024-09-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0005_change_verbose_name_to_help_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="IoTDataToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "token_key_name",
                    models.CharField(
                        default="access_token",
                        help_text="Name of the key where the token is located in the JSON response, e.g., 'access_token'",
                        max_length=64,
                    ),
                ),
                ("user", models.CharField(blank=True, max_length=64, null=True)),
                ("password", models.CharField(blank=True, max_length=64, null=True)),
                ("headers", models.JSONField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
