# Generated by Django 4.2.15 on 2024-09-06 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0006_iotdatatoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="iotdatasource",
            name="token",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_source",
                to="iot.iotdatatoken",
            ),
        ),
        migrations.AddField(
            model_name="iotdatasource",
            name="token_headers",
            field=models.JSONField(
                blank=True,
                help_text='Header used when requesting data with token, e.g., {"Authorization": "Bearer &lt;token&gt;"}, Note, &lt;token&gt; will be replaced with the requested token.',
                null=True,
            ),
        ),
    ]
