# Generated by Django 4.2.15 on 2024-09-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("street_maintenance", "0013_maintenancework_change_related_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GeometryHistory",
        ),
        migrations.RemoveField(
            model_name="maintenancework",
            name="maintenance_unit",
        ),
        migrations.DeleteModel(
            name="MaintenanceUnit",
        ),
        migrations.DeleteModel(
            name="MaintenanceWork",
        ),
    ]
