# Generated by Django 4.1.13 on 2024-04-03 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exceptional_situations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="situationannouncement",
            name="location",
        ),
        migrations.AddField(
            model_name="situationlocation",
            name="announcement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="exceptional_situations.situationannouncement",
            ),
        ),
    ]
