# Generated by Django 4.1.13 on 2024-04-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "exceptional_situations",
            "0002_remove_situationannouncement_location_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="situationannouncement",
            name="title",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="situationannouncement",
            name="title_en",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="situationannouncement",
            name="title_fi",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="situationannouncement",
            name="title_sv",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
