# Generated by Django 4.1.2 on 2023-01-10 12:14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0094_create_syllables_fi_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="search_column_fi_without_syllables",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="unit",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_column_fi_without_syllables"],
                name="services_un_search__90d3f4_gin",
            ),
        ),
    ]
