# Generated by Django 4.2.16 on 2025-11-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0103_unit_geometry_3d"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
