# Generated by Django 4.2.15 on 2024-09-24 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0103_unit_geometry_3d"),
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("UNDEFINED", "undefined"),
                            ("USABLE", "usable"),
                            ("UNUSABLE", "unusable"),
                        ],
                        default="UNDEFINED",
                        max_length=16,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("SKI_TRAIL", "ski_trail"),
                            ("ICE_TRACK", "ice_track"),
                        ],
                        default="SKI_TRAIL",
                        max_length=16,
                    ),
                ),
                ("maintained_at", models.DateTimeField()),
                (
                    "last_imported_time",
                    models.DateTimeField(help_text="Time of last data import"),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance",
                        to="services.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["-maintained_at"],
            },
        ),
    ]
