# Generated by Django 4.2.15 on 2024-09-24 10:08

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0002_unitmaintenance"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitMaintenanceGeometry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometry_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        null=True, srid=4326
                    ),
                ),
                (
                    "unit_maintenance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="geometries",
                        to="maintenance.unitmaintenance",
                    ),
                ),
            ],
        ),
    ]
