# Generated by Django 4.2.15 on 2024-10-02 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0003_unitmaintenancegeometry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitmaintenancegeometry",
            name="unit_maintenance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="geometries",
                to="maintenance.unitmaintenance",
            ),
        ),
    ]
