# Generated by Django 4.2.15 on 2024-10-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "maintenance",
            "0004_alter_unitmaintenancegeometry_unit_maintenance_cascade_deletion",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitmaintenance",
            name="maintained_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
