# Generated by Django 4.2.15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0005_alter_unitmaintenance_maintained_at_to_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitmaintenancegeometry",
            name="unit_maintenance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="geometries",
                to="maintenance.unitmaintenance",
            ),
        ),
    ]
