# Generated by Django 4.2.26 on 2026-02-20 08:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "eco_counter",
            "0024_data_migration_remove_useless_entities_and_updated_relations",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="daydata",
            name="value_sk",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="daydata",
            name="value_sp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="daydata",
            name="value_st",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="hourdata",
            name="values_sk",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="hourdata",
            name="values_sp",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="hourdata",
            name="values_st",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="monthdata",
            name="value_sk",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="monthdata",
            name="value_sp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="monthdata",
            name="value_st",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weekdata",
            name="value_sk",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weekdata",
            name="value_sp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weekdata",
            name="value_st",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="yeardata",
            name="value_sk",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="yeardata",
            name="value_sp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="yeardata",
            name="value_st",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
